//! Match row linking a user profile to a scored lead.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::MatchStatus;

/// A scored job lead linking a user profile to a scraped message.
///
/// Returned by `GET /feed` and pushed via `match.new` WebSocket events.
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct MatchRow {
    /// UUID of the match row in the `matches` table.
    pub id: Uuid,
    /// User this match belongs to.
    pub user_id: Uuid,
    /// The enriched lead this match scored against.
    pub lead_id: Uuid,
    /// AI-computed relevance score 0.0–1.0.
    pub score: f32,
    /// One-sentence reason for the score, generated by the user's AI.
    pub reason: String,
    /// Current lifecycle state of this match.
    pub status: MatchStatus,
    /// When this match was created.
    pub created_at: DateTime<Utc>,
}
