/**
 * Shared API types used across composables, pages, and components.
 * All fields mirror the Rust `core` crate domain types.
 */

/**
 * Raw scraped message that triggered a lead match.
 */
export interface Message {
  /** UUID of the message row. */
  id:         string
  /** Full text content of the job posting. */
  content:    string
  /** Source platform. */
  source:     'telegram' | 'web'
  /** Channel name or URL where the message was found. */
  channel:    string
  /** ISO 8601 timestamp of original posting. */
  posted_at:  string
  /**
   * Budget parsed from the posting text, in RUB. Undefined when no budget is mentioned.
   * Displayed as a prominent price label on the lead card.
   */
  budget_rub?: number
}

/**
 * A scored job lead returned by `GET /feed` and pushed via `match.new` WebSocket events.
 */
export interface FeedItem {
  /** UUID of the match row in the `matches` table. */
  id: string
  /**
   * AI-computed relevance score 0.0–1.0.
   * ≥0.9 perfect · 0.7–0.9 strong · 0.5–0.7 possible · <0.5 poor
   */
  score: number
  /** One-sentence reason for the score, generated by the user's AI provider. */
  reason: string
  /** Current lifecycle state of this match. */
  status: 'pending' | 'ready' | 'delivered' | 'rejected' | 'applied'
  /** The raw job posting that triggered this match. */
  message: Message
}

/**
 * Active filter state bound to FilterBar and passed to useFeed.
 */
export interface FeedFilters {
  /** Minimum score threshold 0.0–1.0; matches below this are hidden. */
  minScore:  number
  /** Include Telegram source leads. */
  telegram:  boolean
  /** Include web (Upwork etc.) source leads. */
  web:       boolean
}
