[package]
name    = "parser_tg"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "parser_tg"
path = "src/main.rs"

[lib]
name = "parser_tg"
path = "src/lib.rs"

[dependencies]
lh_core     = { path = "../core" }
anyhow      = { workspace = true }
async-trait = "0.1"
serde       = { workspace = true }
serde_json  = { workspace = true }
sqlx        = { workspace = true }
redis       = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy     = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
sha2        = "0.10"

[dev-dependencies]
tempfile = "3"
